image: minds/ci-front:latest

stages:
  - test
  - build
  - prepare
  - review
  - deploy:staging
  - qa
  - deploy:canary
  - deploy:production
  - cleanup

variables:
  CYPRESS_INSTALL_BINARY: 0 # Speeds up the install process
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

test:
  image: circleci/node:13-browsers
  stage: test
  script:
    - npm ci
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

lint:
  stage: test
  script:
    - npm i -g prettier@"^1.19.1"
    - prettier --check "src/**/*.ts"
    - prettier --check "src/**/*.scss"
    - prettier --check "src/**/*.html"

############
# QA Stage #
############
.cypress_tests: &cypress_tests
  image: cypress/browsers:node10.16.0-chrome77
  stage: qa
  variables:
    CYPRESS_INSTALL_BINARY: 4.3.0 
  script:
    - npm ci
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        export E2E_DOMAIN=https://www.minds.com
        export PRODUCTION=true
      else
        export E2E_DOMAIN=https://$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
        export PRODUCTION=false
      fi
    - export CYPRESS_baseUrl=$E2E_DOMAIN
    - echo "E2E tests for $CI_BUILD_REF_NAME running against $E2E_DOMAIN with user $CYPRESS_username"
    - $(npm bin)/cypress run --browser chrome --record --key $CYPRESS_RECORD_ID --config CYPRESS_baseUrl=$E2E_DOMAIN,video=false --env captcha_bypass_key=$CYPRESS_bypass_key,production=$PRODUCTION,captcha_shared_key=$CYPRESS_shared_key
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
  cache:
    paths:
      - .npm
      - cache/Cypress

qa:sandbox:
  allow_failure: false
  except:
    - /^master$/
  <<: *cypress_tests

qa:production:
  allow_failure: true
  only:
    - /^master$/
  <<: *cypress_tests

qa:manual:
  stage: qa
  script:
    - echo "Manually approved"
  when: manual
  only:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci
  allow_failure: false

###############
# Build Stage #
###############

build:review:
  stage: build
  before_script:
    - sed -ri "s|'VERSION'|'$CI_PIPELINE_ID'|" src/environments/environment.prod.ts
  script:
    - npm ci && npm install -g gulp-cli
    - npm run postinstall
    - gulp build.sass --deploy-url=/en && gulp build.sass --deploy-url=/en ##weird build needs to be run twice for now
    - sh build/base-locale.sh dist
    - ng run minds:server:production
    - npm run compile:server
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - dist
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

build:production:en:
  stage: build
  before_script:
    - sed -ri "s|'VERSION'|'$CI_PIPELINE_ID'|" src/environments/environment.prod.ts
  script:
    - npm ci && npm install -g gulp-cli
    - npm run postinstall
    - gulp build.sass --deploy-url=https://cdn-assets.minds.com/front/dist/en && gulp build.sass --deploy-url=https://cdn-assets.minds.com/front/dist/en ##weird build needs to be run twice for now
    - sh build/base-locale.sh dist https://cdn-assets.minds.com/front/dist
    - ng run minds:server:production
    - npm run compile:server
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - dist/en
      - dist/server.js
      - dist/server
  only:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

build:production:i18n:
  stage: build
  before_script:
    - sed -ri "s|'VERSION'|'$CI_PIPELINE_ID'|" src/environments/environment.prod.ts
  script:
    - npm ci && npm install -g gulp-cli
    - npm run postinstall
    - gulp build.sass --deploy-url=https://cdn-assets.minds.com/front/dist/en && gulp build.sass --deploy-url=https://cdn-assets.minds.com/front/dist/en ##weird build needs to be run twice for now
    - sh build/i18n-locales-all.sh dist https://cdn-assets.minds.com/front/dist
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - dist/vi
  only:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

#################
# Prepare Stage #
#################

.sentry_prepare: &sentry_prepare
  stage: prepare
  image: getsentry/sentry-cli
  script:
    - echo "Create a new release $CI_PIPELINE_ID"
    - sentry-cli releases new $CI_PIPELINE_ID
    - sentry-cli releases set-commits --auto $CI_PIPELINE_ID
    - sentry-cli releases files $CI_PIPELINE_ID upload-sourcemaps $CI_PROJECT_DIR/dist/en -x .js -x .map --validate --url-prefix $SOURCEMAP_PREFIX
    - sentry-cli releases finalize $CI_PIPELINE_ID
    - echo "Finalized release for $CI_PIPELINE_ID"

prepare:review:
  stage: prepare
  image: minds/ci:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID -f containers/server/Dockerfile dist/.
    - docker push $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID
  dependencies:
    - build:review
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

prepare:review:sentry:
  <<: *sentry_prepare
  variables:
    SOURCEMAP_PREFIX: '~/en'
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci
  dependencies:
    - build:review

prepare:production:
  stage: prepare
  image: minds/ci:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID -f containers/server/Dockerfile dist/.
    - docker push $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID
    - docker tag $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID $CI_REGISTRY_IMAGE/server:latest
    - docker push $CI_REGISTRY_IMAGE/server:latest
  only:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci
  dependencies:
    - build:production:en
    - build:production:i18n

prepare:production:sentry:
  <<: *sentry_prepare
  variables:
    SOURCEMAP_PREFIX: '~/front/dist/en'
  only:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci
  dependencies:
    - build:production:en
    - build:production:i18n

################
# Review Stage #
################

.cleanup_review: &cleanup_review
  image: minds/helm-eks:latest
  script:
    - aws eks update-kubeconfig --name=sandbox
    - helm del --purge $CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    action: stop
  variables:
    GIT_STRATEGY: none
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

review:start:
  stage: review
  image: minds/helm-eks:latest
  script:
    - aws eks update-kubeconfig --name=sandbox
    - git clone --branch=master https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/minds/helm-charts.git
    - "helm upgrade \
      --install \
      --reuse-values \
      --set front.image.repository=$CI_REGISTRY_IMAGE/server \
      --set-string front.image.tag=$CI_PIPELINE_ID \
      --set domain=$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN \
      --set elasticsearch.clusterName=$CI_BUILD_REF_SLUG--elasticsearch \
      --wait \
      $CI_BUILD_REF_SLUG \
      ./helm-charts/minds"
    # Update sentry
    - sentry-cli releases deploys $CI_PIPELINE_ID new -e review-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_BUILD_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: review:stop
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci

review:stop:
  <<: *cleanup_review
  stage: review
  when: manual

################
# Deploy Stage #
################

.deploy: &deploy
  image: minds/ci:latest
  services:
    - docker:dind
  script:
    ## Sync assets with CDN
    - aws s3 sync dist $S3_REPOSITORY_URL --cache-control max-age=31536000
    - $(aws ecr get-login --no-include-email --region us-east-1)
    ## Update docker server container
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker pull $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID
    - docker tag $CI_REGISTRY_IMAGE/server:$CI_PIPELINE_ID $ECR_REPOSITORY_URL:$IMAGE_LABEL
    - docker push $ECR_REPOSITORY_URL:$IMAGE_LABEL
    ## Deploy the new container in rolling restart
    - aws ecs update-service --service=$ECS_SERVICE --force-new-deployment --region us-east-1 --cluster=$ECS_CLUSTER
    ## Update sentry
    - sentry-cli releases deploys $CI_PIPELINE_ID new -e $IMAGE_LABEL
  dependencies:
    - build:production:en
    - build:production:i18n

staging:fpm:
  <<: *deploy
  stage: deploy:staging
  variables:
    IMAGE_LABEL: 'staging'
    ECS_SERVICE: $ECS_APP_STAGING_SERVICE
  environment:
    name: staging
    url: https://www.minds.com # requires staging cookie
  only:
    refs:
      - master
      - epic/SSR
      - test/gitlab-ci

review:preprod:
  <<: *deploy
  stage: review
  when: manual
  allow_failure: true
  variables:
    IMAGE_LABEL: 'preprod'
    ECS_SERVICE: $ECS_APP_PREPROD_SERVICE
  environment:
    name: preprod
    url: https://www.minds.com # requires preprod cookie
  # dependencies:
  #   - build:review
  # except:
  #   refs:
  #     - master

deploy:canary:
  <<: *deploy
  stage: deploy:canary
  variables:
    IMAGE_LABEL: 'canary'
    ECS_SERVICE: $ECS_APP_CANARY_SERVICE
  environment:
    name: canary
    url: https://www.minds.com/?canary=1 # requires canary cookie
  when: manual
  allow_failure: false # prevents auto deploy to full production
  only:
    refs:
      - master
      - epic/SSR
      - test/gitlab-ci

deploy:production:
  <<: *deploy
  stage: deploy:production
  variables:
    IMAGE_LABEL: 'production'
    ECS_SERVICE: $ECS_APP_PRODUCTION_SERVICE
  environment:
    name: production
    url: https://www.minds.com
  when: delayed
  start_in: 12 hours # reduce? can always be deployed manually earlier too
  only:
    refs:
      - master
      - epic/SSR
      - test/gitlab-ci

#################
# Cleanup stage #
#################

cleanup:review: # We stop the review site after the e2e tests have run
  <<: *cleanup_review
  stage: cleanup
  when: manual
  except:
    refs:
      - master
      - epic/SSR
      - production
      - test/gitlab-ci
